### ISSUE TITLE
Color issue with Pixel Saver extension

### ISSUE THREAD

**Issue by rahilwazir** [sziberov/Poppy-OS-X-Revieve#1]
When using [Pixel Saver](https://extensions.gnome.org/extension/723/pixel-saver/) extension, the color is white by default. This ~only~ happens when **Poppy-OS-X-Revieve** is selected as **Shell Theme**. Of course all shell themes with white color shades have this issue.

![pixel-saver](https://user-images.githubusercontent.com/1818941/30196444-3549184e-947a-11e7-908e-3931bf31d6eb.png)

**Desktop Manager**: Gnome (v3.24.3)

**Comment by i-am-dies** [comment]
I don't have this "X" icon and any other things like you show here when Pixel Saver enabled.

Also, if I correctly understand description of extension, you should not use it with my theme, as toolbar, titlebar and other things have correct height already, identical to OS X's or maximally similar.

My menubar look like this now (P. S. is enabled)
![2017-09-08 14-34-26](https://user-images.githubusercontent.com/7362968/30210077-9ccde3d6-94a3-11e7-9f08-1c0cdb6a4c81.png)

**Comment by i-am-dies** [comment]
Uh oh, I see now.
![2017-09-08 14-43-41](https://user-images.githubusercontent.com/7362968/30210159-1ffacae4-94a4-11e7-8ffd-8e7fb3b922d1.png)


So what we have there? This ext using different icons for a theme it knows, and this by default:
![2017-09-08 14-45-15](https://user-images.githubusercontent.com/7362968/30210199-5cabcb5a-94a4-11e7-90b2-3786a1061246.png)

You should ask developer to contact with me here, if you want correct color and all other styling for this buttons.

**Comment by sziberov** [comment]
So what we have there? This ext using different icons for a theme it knows, and this by default:
![2017-09-08 14-45-15](https://user-images.githubusercontent.com/7362968/30210199-5cabcb5a-94a4-11e7-90b2-3786a1061246.png)

You should ask developer to contact with me here, if you want correct color and all other styling for this buttons.

**Comment by rahilwazir** [comment]
Sorry I was not clear with my description. When you MAXIMIZE any application, the ~action icons~ window controls then displays on gnome shell (depending on the position top/bot).

Anyways, I'll report there and see what they say!

**Comment by rahilwazir** [comment]
Can you provide me the correct color and styling for these buttons? I'll fork **Pixel Saver** and submit pull-request if all works well.

**Comment by i-am-dies** [comment]
@rahilwazir Yes, I will send you archive soon.

**Comment by i-am-dies** [comment]
@rahilwazir [POSX.zip](https://github.com/sziberov/Poppy-OS-X-Revieve/files/1305727/POSX.zip)

**Comment by rahilwazir** [comment]
Thank you so much, I'll try out this over weekend.

**Comment by rahilwazir** [comment]
I have tested and it's working correctly...

![min-max-close](https://user-images.githubusercontent.com/1818941/30510175-7e64404e-9ad8-11e7-8754-75208d2ea857.png)

... but with an exception. The `-gtk-scaled` value is not working. When I remove it and simply use the `url(...)` value its working fine.

![background-image](https://user-images.githubusercontent.com/1818941/30510188-ad2de1b4-9ad8-11e7-9db4-76823af8334c.png)

Do you know why is that? Checkout this branch, if you want to try out, here: https://github.com/rahilwazir/pixel-saver/tree/theme-poppy-osx-revieve

**Comment by i-am-dies** [comment]
@rahilwazir Can I close the issue? I understood that I need to remove spaces and version in the theme folder name for future releases support, but this is incorrect to have shitty `-` insead of spaces and no version in it for me.

**Comment by rahilwazir** [comment]
@sziberov You should better off using [Git Tags](https://git-scm.com/book/en/v2/Git-Basics-Tagging) instead of creating new folder for each version.

> The -gtk-scaled value is not working. When I remove it and simply use the url(...) value its working fine.

Can you please answer me this if you know by chance?

Other than that we can close this 😄

**Comment by i-am-dies** [comment]
@rahilwazir No, this incorrect, I should not be Git-depended. I could just use releases if I want.

**Comment by rahilwazir** [comment]
@sziberov No problem, it's totally upto you. I was just recommending the GIT way.

Again.... can you please answer this? 😄

> The -gtk-scaled value is not working. When I remove it and simply use the url(...) value its working fine.

**Comment by i-am-dies** [comment]
@rahilwazir This can be gnome shell (mutter) limitation.

**Comment by rahilwazir** [comment]
Alright. I'll send PR on pixel saver repo and let's see if they merge it or not. Thank you for the info.
