### ISSUE TITLE
Google Chrome maximize icon is missing

### ISSUE THREAD

**Issue by rahilwazir** [sziberov/Poppy-OS-X-Revieve#2]
When maximizing Google Chrome (Unstable 62.x) the maximize icon is replaced by weird character.

Unmaximized:
![unmaximize](https://user-images.githubusercontent.com/1818941/30196612-76b10980-947b-11e7-85f6-55ee0da1423e.png)

Maximized:
![maximize](https://user-images.githubusercontent.com/1818941/30196613-7a1aec30-947b-11e7-8ca7-51ad93b256df.png)

The maximized character changes respective to icons, so maybe it's something to do with theme icons? not sure.
Which theme icon you will recommend?

**Desktop Manager:** Gnome (v3.24.3)

**Comment by i-am-dies** [comment]
I didn't know why this happens and don't have seen this before.

Currently I'm using my own icons based (earlier is not) on the 'la-capitaine-icon-theme-0.4', and that not released for now. You can give me your email adress, I will send you archive if you want, but please be reasonable and don't post it everywhere before official release (and yes, sounds like embargo).

**Comment by i-am-dies** [comment]
Additionally, you can check out if this bug appears in 'Gn-OSX-HSierra-1.2-sidebar-issue' theme.

**Comment by rahilwazir** [comment]
I tested with the **'Gn-OSX-HSierra-1.2-sidebar-issue** theme but still same issue.

Maximized:
![still](https://user-images.githubusercontent.com/1818941/30213566-d43ff920-94c2-11e7-806a-0881f666887a.png)

UnMaximize:
![fine](https://user-images.githubusercontent.com/1818941/30213565-d42f10ba-94c2-11e7-8612-342c8f5faf98.png)

Not really looking for the icons, just wanted to know what you were using, just announce in the Readme once you publish publicly.

**Comment by i-am-dies** [comment]
@rahilwazir So as we can see: problem also presents in theme I'm basing on. Report this in comments here - [https://www.opendesktop.org/p/1180505/](url) - and if problem get fixed I look what I can do.

And did you tried to disable all of your extensions?

**Comment by rahilwazir** [comment]
> Report this in comments here - https://www.opendesktop.org/p/1180505/ - and if problem get fixed I look what I can do.

Reported in the comments.

> And did you tried to disable all of your extensions?

Yes, I disabled all extensions, issue persists

**Comment by i-am-dies** [comment]
@rahilwazir Then it can be your DE too.

**Comment by rahilwazir** [comment]
> Then it can be your DE too.

Don't you think it has to do with Google Chrome itself? Setting different themes like Arc, Adwaita shows the maximize just fine.

**Comment by i-am-dies** [comment]
@rahilwazir > Don't you think it has to do with Google Chrome itself?

All buttons set in one way for all apps, and I don't know how the fuck only 'maximize' is bugged for Chrome.

**Comment by rahilwazir** [comment]
Haha oops 😄 (let's not use bad words here). Don't worry we will figure it out 😛 

But is it working fine at your end in Chrome? Can you share a screenshot

**Comment by i-am-dies** [comment]
![2017-09-08 19-03-54](https://user-images.githubusercontent.com/7362968/30220576-9ceb3d26-94c8-11e7-8f4c-dce7666eaa67.png)

Installing Chrome in 17.04 is hell, so browser on screen' - Chromium. It mostly the same.

**Comment by rahilwazir** [comment]
Hmm well [this](https://www.google.com/chrome/browser/desktop/index.html?platform=linux&extra=devchannel) should work just fine, no complication tho and you will get your distro related package.

I just installed Chromium (v60.x) and I see where we are getting. Your screenshot suggests that you have enabled **Use system title bar and borders** in the Settings which creates it's own title bar on top of the browser. And the case I reported have the option **Use system title bar and borders** disabled (This is regardless of which Chrome we use).

Can you try to disable and restart your browser and check the issue exist?

**Comment by i-am-dies** [comment]
@rahilwazir Now I have standart for gtk2 browser clearlook buttons and pretty noised (.headerbar/.titlebar) background ![2017-09-08 19-41-54](https://user-images.githubusercontent.com/7362968/30221941-cfac903e-94cd-11e7-9700-cd06092edcfe.png)

**Comment by rahilwazir** [comment]
Argh, right this is same for me when using Chromium, GTK version title bars. So I think it's happening on Chrome dev branch. Have you tried installing Chrome dev from my previous comment and try to reproduce?

**Comment by i-am-dies** [comment]
@rahilwazir No, I will try this right now.

Well, nope. I have 32bit distro and here links only for 64bit.

**Comment by rahilwazir** [comment]
Ok let's defer it for the moment!
