### ISSUE TITLE
Alignment issue of Application icon with Dash to Panel

### ISSUE THREAD

**Issue by rahilwazir** [sziberov/Poppy-OS-X-Revieve#3]
When using [Dash to Panel](https://extensions.gnome.org/extension/1160/dash-to-panel/) extension the application icon losts it's alignment when **Shell theme** is set to **Poppy-OS-X-Revieve**
![shell-theme](https://user-images.githubusercontent.com/1818941/30196787-a6301948-947c-11e7-88db-4177f2b6898a.png)

**Desktop Manager**: Gnome (v3.24.3)

**Comment by i-am-dies** [comment]
Don't know how to fix this, sorry. I need to set some fixed padding for properly looking image of blue "dot".
![2017-09-15 08-53-29](https://user-images.githubusercontent.com/7362968/30468340-7014a08c-99f3-11e7-8f9e-201ae5072429.png)

**Comment by rahilwazir** [comment]
Not sure I understand, but were you able to reproduce it using **Dash to Panel**?

**Comment by i-am-dies** [comment]
@rahilwazir Yes, this icon is horizontally wided and centered to top.

**Comment by rahilwazir** [comment]
But may I know why is that, can I see your screenshot to perceive it more clearly?

**Comment by i-am-dies** [comment]
@rahilwazir You want to see 'why' or what I looking at now? Becuase I need to test some changes in css for be sure I know where problem is.
![2017-09-15 09-01-09](https://user-images.githubusercontent.com/7362968/30468583-d8b0359c-99f4-11e7-9c36-f1b4ac9866f9.png)

**Comment by rahilwazir** [comment]
Thanks, take your time.

**Comment by i-am-dies** [comment]
@rahilwazir I got it to be fixed for DashToPanel, but not for DashToDock then.

![2017-09-15 09-10-39](https://user-images.githubusercontent.com/7362968/30468803-e5e59f1c-99f5-11e7-9a9f-d8a5cc204219.png)

**Comment by rahilwazir** [comment]
Oh, is there not a something like parent selector to fix for DashToDock (as we do in CSS) ? I'm really sorry I'm not that experience with GTK themes CSS 😄

**Comment by i-am-dies** [comment]
Ok, using two slightly different CSS properties now working properly.
![2017-09-15 09-14-43](https://user-images.githubusercontent.com/7362968/30468878-559bb968-99f6-11e7-9ca7-ba2733559c5a.png)

**Comment by i-am-dies** [comment]
@rahilwazir Place file from this archive in gnome-shell folder in theme root.
[gnome-shell.css.zip](https://github.com/sziberov/Poppy-OS-X-Revieve/files/1305445/gnome-shell.css.zip)

**Comment by rahilwazir** [comment]
Awesome thank you its fixed!
![fixed](https://user-images.githubusercontent.com/1818941/30469025-dbb09788-9a07-11e7-8ce3-ece7dda68159.png)

**Comment by rahilwazir** [comment]
And please don't forget to update the repository with the changes 👍
