### ISSUE TITLE
Icons and text are very light in shell

### ISSUE THREAD

**Issue by rahilwazir** [sziberov/Poppy-OS-X-Revieve#4]
The settings, power and screen rotate icons are very light oppose to the white background.

![light-icons](https://user-images.githubusercontent.com/1818941/30470924-251a33f4-9a10-11e7-8021-a5ca1acc9f0c.png)

Can we make it a bit darker? The screen rotate icon is barely visible 👀

**Comment by rahilwazir** [comment]
Another similar issue but with text:

![calendar](https://user-images.githubusercontent.com/1818941/30471019-8ebf7da0-9a10-11e7-8135-4662ac96a908.png)

**Comment by i-am-dies** [comment]
Fixed.

**Comment by rahilwazir** [comment]
Yes, its fixed BUT another issue after updating this. That the application title font size has increased and looks very bad 😭 (please bring back the old fonts)

![ugly](https://user-images.githubusercontent.com/1818941/30477217-d1425a34-9a25-11e7-9cd8-b69baaeb843b.png)

**Comment by i-am-dies** [comment]
@rahilwazir Have you installed what I placed in 'Required Fonts' folder?

It should look thinner.
![2017-09-15 12-59-26](https://user-images.githubusercontent.com/7362968/30477426-c5f20e64-9a15-11e7-9699-dbc766e81538.png)

**Comment by rahilwazir** [comment]
Oh damn! It looks beautiful now thank you.

Do these fonts suppose to be installed automatically Or it's upto the user to install them? If it's the latter case please mention this in Readme file, so the public will know 🤓

**Comment by i-am-dies** [comment]
@rahilwazir Font's can't be auto-installed with theme, user need to install it manually.

**Comment by rahilwazir** [comment]
Sorry what I meant by auto-installed is that wouldn't CSS pick the font familly if we import to the CSS, like we do in web browser? Sorry if it's a stupid question
```css
@font-face {
   font-family: Myriad....
....
```

**Comment by i-am-dies** [comment]
@rahilwazir I didn't tried, but this will probably not work anyway.
